### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [cybre/RedshiftGtk#1]
Hello,
I was wondering is this project still alive?

**Comment by cybre** [comment]
@Ashutosh-Kukreti Hello. It's not actively developed at the moment but I wouldn't say it's dead. I will get back to it as soon as I find some free time and install a linux distribution again.

**Comment by Ashutosh-Kukreti** [comment]
Thank you for replying :)
I hope it will be developed soon.
Maybe you can contact the redshift developer he can help you or any other linux dev on reddit.
There are many people out there who are a fan of redshift.
